#!/bin/bash

set -e

git stash save "prePush" -q --keep-index


function unstash {
	git stash apply stash^{/prePush} -q || true
}

trap unstash EXIT


./gradlew detektCheck checkstyle checkstyleMain checkstyleTest -q --daemon